### ISSUE TITLE
Generate Video Error

### ISSUE THREAD

**Issue by Lotayou** [sergeytulyakov/mocogan#8]
I was trying to generate some videos using the generated_video script, and I was encountering the following error:

I don't know why this error will happen in testing, not in training? We generate fake video clips in training as well, no? Why am I encountering this error at test stage? 

Can anyone tell me why this would happen? Thanks!

`
Traceback (most recent call last):
 File "/home/eric/mocogan/src/generate_videos.py", line 61, in <module>
    v, _ = generator.sample_videos(1, int(args['--number_of_frames']))
`
`
  File "/home/eric/mocogan/src/models.py", line 285, in sample_videos
    z, z_category_labels = self.sample_z_video(num_samples, video_len)
`
`
  File "/home/eric/mocogan/src/models.py", line 273, in sample_z_video
    z_motion = self.sample_z_m(num_samples, video_len)
`
`
  File "/home/eric/mocogan/src/models.py", line 227, in sample_z_m
    h_t.append(self.recurrent(e_t, h_t[-1]))
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 729, in forward
    self.bias_ih, self.bias_hh,
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 50, in GRUCell
    gi = F.linear(input, w_ih)
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 837, in linear
    output = input.matmul(weight.t())
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 386, in matmul
    return torch.matmul(self, other)
`
`
  File "/home/eric/anaconda3/lib/python3.6/site-packages/torch/functional.py", line 174, in matmul
    return torch.mm(tensor1, tensor2)
`
`
RuntimeError: Expected object of type Variable[torch.cuda.FloatTensor] but found type Variable[torch.FloatTensor] for argument #1 'mat2'
`

**Comment by Lotayou** [comment]
The problem is resolved after I loaded model into cuda gpu instead of cpu. Thanks!
